services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  
  userapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: userapp
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      - postgres